version: '3.0'

services:
  grafana:
    container_name: 'hagal-datasource'
    platform: "linux/amd64"
    build:
      context: ./.config
      args:
        grafana_image: grafana
        grafana_version: latest
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/hagal-datasource
      - ./provisioning:/etc/grafana/provisioning
    environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin
        - GF_SECURITY_ADMIN_USER=admin
        - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=hagal-datasource
